INSERT INTO tb_worker (name, daily_Income) VALUES ('Bob', 200.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Maria', 300.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Alex', 250.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Marcio', 800.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Sombra', 658.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Motta', 45.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Carlos Humberto', 987.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Mano Borges', 156.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Seô Bento', 4.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Salscicha', 45.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Fernando Camargo', 8.60);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Rogério', 789.70);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Amanda', 234.40);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Maria', 45.60);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Luciana', 234.07);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Victor', 234.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Everton', 76.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Zé Henrique', 45645.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Marcão', 767.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Fulano', 567.80);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Beltrano', 908.09);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Sicrano', 98.80);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Palmeiras', 345.40);
INSERT INTO tb_worker (name, daily_Income) VALUES ('São Paulo', 674.50);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Corinthians', 334.50);